Repository dan-lynch/trackportfol.io, pull requests merged in 2020-06, with the labels that each got.

#30 add unit tests using enzyme
  client/package.json
  client/src/components/InstrumentView.test.tsx
  client/src/components/Join.test.tsx
  client/src/components/Login.test.tsx
  client/src/components/ProtectedRoute.test.tsx
  client/src/components/__snapshots__/InstrumentView.test.tsx.snap
  client/src/components/__snapshots__/Join.test.tsx.snap
  client/src/components/__snapshots__/Login.test.tsx.snap
  client/src/components/__snapshots__/ProtectedRoute.test.tsx.snap
  client/src/layout/Header.test.tsx
  client/src/layout/__snapshots__/Header.test.tsx.snap
  client/src/pages/Join.test.tsx
  client/src/pages/__snapshots__/Join.test.tsx.snap
  client/src/services/fetchStockData.tsx
  client/yarn.lock
  package.json
Labels: enhancement

#31 upgrade to new apollo client, cleanup dependencies
  client/package.json
  client/src/App.tsx
  client/src/Router.tsx
  client/src/components/Dashboard.tsx
  client/src/components/InstrumentView.tsx
  client/src/components/Join.tsx
  client/src/components/Login.tsx
  client/src/components/SearchStock.tsx
  client/src/index.tsx
  client/src/layout/MainLayout.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Join.tsx
  client/src/pages/Login.tsx
  client/src/services/fetchStockData.tsx
  client/src/services/userService.ts
  client/src/utils.tsx
  client/yarn.lock
Labels: enhancement

#33 add favicon and logo
  client/public/favicon.ico
  client/public/logo192.png
  client/public/logo512.png
Labels: enhancement

#34 setup deploy scripts for db and graphql
  .env
  .env.gpg
  .github/workflows/deploy-client.yml
  .github/workflows/deploy-db.yml
  .github/workflows/deploy-graphql.yml
  backend/db/init/00-database.sql.gpg
  backend/db/init/01-functions-1.sql.gpg
  backend/db/init/02-functions-2.sql.gpg
  backend/db/init/03-policies.sql.gpg
  backend/db/init/04-instruments.sql.gpg
  decrypt_schema.sh
  encrypt_schema.sh
Labels: enhancement

#35 create new dockerfiles for deploying
  .github/workflows/deploy-db.yml
  .github/workflows/deploy-graphql.yml
  backend/db/Dockerfile.deploy
  backend/graphql/Dockerfile.deploy
Labels: bug

#36 fix workflow scripts
  .github/workflows/deploy-db.yml
  .github/workflows/deploy-graphql.yml
Labels: bug

#39 improve layout, add side menu, dark theme
  client/components/Header.tsx
  client/components/InstrumentView.tsx
  client/components/Layout.tsx
  client/components/LoggedInHeader.tsx
  client/components/LoggedOutHeader.tsx
  client/components/SearchStock.tsx
  client/pages/dashboard.tsx
  client/pages/index.tsx
  client/pages/join.tsx
  client/pages/login.tsx
  client/theme.tsx
Labels: enhancement

#46 Test deploy
  .github/workflows/deploy-db.yml
  .github/workflows/deploy-graphql.yml
  backend/db/Dockerfile.deploy
  backend/graphql/Dockerfile.deploy
  decrypt_protected_files.sh
Labels: API, bug

#61 add dark theme toggle
  client/components/LoggedInHeader.tsx
  client/context/AppContext.tsx
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/theme.tsx
Labels: Front-End, enhancement

#63 upgrade api
  .env.gpg
  backend/db/init/00-database.sql.gpg
  backend/db/init/00-tables.sql.gpg
  backend/db/init/01-functions-1.sql.gpg
  backend/db/init/01-functions.sql.gpg
  backend/db/init/02-functions-2.sql.gpg
  backend/db/init/02-policies.sql.gpg
  backend/db/init/03-instruments.sql.gpg
  backend/db/init/03-policies.sql.gpg
  backend/db/init/04-instruments.sql.gpg
  client/pages/dashboard.tsx
  client/pages/join.tsx
  client/pages/login.tsx
  client/services/graphql/index.ts
  client/services/graphql/mutations/createHolding.ts
  client/services/graphql/mutations/currentUser.ts
  client/services/graphql/mutations/deleteHolding.ts
  client/services/graphql/mutations/index.ts
  client/services/graphql/mutations/register.ts
  client/services/graphql/mutations/updateHolding.ts
  client/services/graphql/queries/currentUser.ts
  client/services/graphql/queries/index.ts
  client/services/userService.ts
  decrypt_protected_files.sh
  encrypt_protected_files.sh
Labels: API, enhancement

#66 user theme preference, change login and register to modals, tidy up
  client/.prettierrc.js
  client/components/Header/LoggedInHeader.tsx
  client/components/Header/LoggedOutHeader.tsx
  client/components/InstrumentView.tsx
  client/components/Join.tsx
  client/components/Layout.tsx
  client/components/Layout/LoggedInLayout.tsx
  client/components/Layout/LoggedOutLayout.tsx
  client/components/Link.tsx
  client/components/LoggedOutHeader.tsx
  client/components/Login.tsx
  client/components/SearchStock.tsx
  client/components/StockChart.tsx
  client/components/withApollo.tsx
  client/context/AppContext.tsx
  client/helpers/constants.ts
  client/helpers/handleResponse.ts
  client/helpers/misc.ts
  client/helpers/theme.tsx
  client/helpers/types.ts
  client/helpers/utils.tsx
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/dashboard.tsx
  client/pages/index.tsx
  client/services/apolloService.ts
  client/services/fetchStockData.tsx
  client/services/gaService.ts
  client/services/graphql/index.ts
  client/services/graphql/mutations/createHolding.ts
  client/services/graphql/mutations/currentUser.ts
  client/services/graphql/mutations/deleteHolding.ts
  client/services/graphql/mutations/index.ts
  client/services/graphql/mutations/login.ts
  client/services/graphql/mutations/register.ts
  client/services/graphql/mutations/updateHolding.ts
  client/services/graphql/mutations/updateTheme.ts
  client/services/graphql/queries/allInstruments.ts
  client/services/graphql/queries/index.ts
  client/services/graphql/queries/searchInstruments.ts
  client/services/userService.ts
Labels: Front-End, enhancement

#68 update project structure
  .github/workflows/deploy-api.yml
  .github/workflows/deploy-db.yml
  .gitignore
  .nginx/reverseproxy_nginx.conf
  README.md
  api/Dockerfile
  api/index.js
  api/package.json
  api/tsconfig.json
  api/yarn.lock
  db/Dockerfile
  db/init/00-tables.sql.gpg
  db/init/01-functions.sql.gpg
  db/init/02-policies.sql.gpg
  db/init/03-instruments.sql.gpg
  db/package.json
  decrypt_protected_files.sh
  docker-compose.api.yml
  docker-compose.db.yml
  encrypt_protected_files.sh
Labels: documentation, enhancement

#74 add new account page
  client/components/Header/LoggedInHeader.tsx
  client/context/AppContext.tsx
  client/pages/account.tsx
  client/pages/dashboard.tsx
  client/services/graphql/index.ts
  client/services/graphql/mutations/currentUser.ts
  client/services/graphql/mutations/getUserEmail.tsx
  client/services/graphql/mutations/index.ts
  client/services/graphql/mutations/updateUserEmail.tsx
  client/services/graphql/mutations/updateUserPassword.tsx
  client/services/graphql/mutations/updateUsername.tsx
  client/services/userService.ts
Labels: Front-End, enhancement

#76 dont render before username fetched
  client/pages/account.tsx
Labels: enhancement

#82 upgrade login form
  .gitignore
  client/components/Join.tsx
  client/components/Login.tsx
  client/package.json
  client/pages/index.tsx
  client/yarn.lock
Labels: Front-End, enhancement

#84 adding margin between edit and delete
  client/components/HoldingView.tsx
  client/pages/dashboard.tsx
Labels: Front-End, enhancement

#85 store theme in separate cookie
  client/components/Header/LoggedInHeader.tsx
  client/components/Login.tsx
  client/context/AppContext.tsx
  client/helpers/constants.ts
  client/pages/_document.tsx
  client/services/userService.ts
Labels: Front-End, enhancement

#87 update holding view with prices
  client/components/HoldingView.tsx
  client/helpers/types.ts
  client/package.json
  client/pages/dashboard.tsx
  client/services/graphql/mutations/createHolding.ts
  client/services/graphql/mutations/currentUser.ts
  client/services/graphql/mutations/deleteHolding.ts
  client/services/graphql/mutations/updateHolding.ts
  client/yarn.lock
Labels: Front-End, enhancement

#94 GraphQL Subscriptions
  .env.gpg
  api/index.js
  api/package.json
  api/tsconfig.json
  api/yarn.lock
  client/.env.development
  client/.env.production
  client/components/HoldingView.tsx
  client/components/Join.tsx
  client/components/Login.tsx
  client/helpers/constants.ts
  client/package.json
  client/pages/account.tsx
  client/pages/dashboard.tsx
  client/services/apolloService.ts
  client/services/graphql/index.ts
  client/services/graphql/mutations/currentUser.ts
  client/services/graphql/mutations/deleteHolding.ts
  client/services/graphql/mutations/getUserEmail.tsx
  client/services/graphql/mutations/index.ts
  client/services/graphql/mutations/login.ts
  client/services/graphql/mutations/registerUser.ts
  client/services/graphql/mutations/updateHolding.ts
  client/services/graphql/queries/authenticate.ts
  client/services/graphql/queries/currentUser.ts
  client/services/graphql/queries/getUserEmail.tsx
  client/services/graphql/queries/index.ts
  client/services/graphql/queries/searchInstruments.ts
  client/services/graphql/subscriptions/index.ts
  client/services/graphql/subscriptions/subscribeCurrentUser.ts
  client/services/userService.ts
  client/yarn.lock
  db/Dockerfile
  db/init/00-tables.sql.gpg
  db/init/01-functions.sql.gpg
  db/init/02-policies.sql.gpg
  db/init/03-instruments.sql.gpg
  db/init/04-config-script.sh
  db/package.json
  docker-compose.api.yml
  graphql-examples.md
  package.json
Labels: API, Front-End, enhancement

#96 replace subscription with query polling, fix routing to dashboard
  client/components/Login.tsx
  client/pages/dashboard.tsx
  client/pages/index.tsx
  client/services/apolloService.ts
Labels: Front-End, bug, enhancement

#97 prepare deployment for aws migration
  .env.gpg
  .github/workflows/deploy-db.yml
  .nginx/react_nginx.conf
  .nginx/reverseproxy_nginx.conf
  .nginx/trackportfol.io.conf
  api/package.json
  client/package.json
  db/package.json
  manual_deploy.sh
  package.json
Labels: enhancement

#100 re-enable live queries, disable graphiql in prod
  api/index.js
  client/.env.development
  client/.env.production
  client/helpers/constants.ts
  client/pages/dashboard.tsx
  client/services/apolloService.ts
Labels: Front-End, enhancement
